# Generated by Django 4.1.1 on 2022-09-07 07:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geek',
            name='geeks_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=200),
        ),
    ]
